# Generated by Django 4.2.6 on 2024-01-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0002_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
